### ISSUE TITLE
关于P2661的vector segment fault问题

### ISSUE THREAD

**Issue by WenzeJin** [spicyGrape/Luogu_With_Comments#1]
在你的代码当中，一个二维vector被如下声明：  

```C++
vector<vector<int>> inf;
```

紧接着，你使用了下标对vector进行访问，但是目前vector内一个元素都没有呀！

**Comment by WenzeJin** [comment]
关于修改建议，为了达到跳跃式访问的兼容，可以重写一个Vector类实现对`stl::vector`的简单封装，达到的效果为当访问下标超过`vector.size()`时，先把vector扩充到一个合理的容量。

**Comment by WenzeJin** [comment]
`std::vector`

**Comment by spicyGrape** [comment]
感谢！是很合理的建议，我会在以后的代码中尝试使用这个技巧。
